name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Windows
      run: cd ./src/IDP/ && dotnet publish -c release -r win10-x64
    - name: Zip Windows Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'idp-win10-x64.zip'
        path: ./src/IDP/bin/release/netcoreapp3.1/win10-x64/publish/
    - name: Publish Linux
      run: cd ./src/IDP/ && dotnet publish -c release -r linux-x64
    - name: Zip Linux Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'idp-linux-x64.zip'
        path: ./src/IDP/bin/release/netcoreapp3.1/linux-x64/publish/
    - name: Publish OSX
      run: cd ./src/IDP/ && dotnet publish -c release -r osx.10.11-x64
    - name: Zip OSX Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'idp-osx.10.11-x64.zip'
        path: ./src/IDP/bin/release/netcoreapp3.1/osx.10.11-x64/publish/
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        release_name: Release ${{ steps.vars.outputs.tag }}
        draft: false
        prerelease: false    
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./idp-win10-x64.zip
        asset_name: idp-win10-x64.zip
        asset_content_type: application/zip  
    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./idp-linux-x64.zip
        asset_name: idp-linux-x64.zip
        asset_content_type: application/zip 
    - name: Upload OSX Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./idp-osx.10.11-x64.zip
        asset_name: idp-osx.10.11-x64.zip
        asset_content_type: application/zip    