name: Prerelease

on:
  push:
    branches: [ develop ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Windows
      run: cd ./src/IDP/ && dotnet publish -c release -r win10-x64
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'idp-win10-x64.zip'
        path: ./src/IDP/bin/release/netcoreapp3.1/win10-x64/publish/
    